apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-config
data:
  employee.properties: |
    spring.application.name=employee
    server.port=8080
    management.endpoints.web.base-path=/actuator
    management.endpoints.web.exposure.include=health,info,env
    spring.cloud.config.fail-fast=true
